### PR TITLE
Add missing dependencies and Update README

### PR DESCRIPTION
**Pull request by tiagomartinho**

### CODE REVIEW

**Comment by ianpartridge** [comment]
I want to keep this repo targetting Ubuntu 14.04 as the IBM-Swift team use it for building environments to target Cloud Foundry, which also uses 14.04.

**Comment by tiagomartinho** [comment]
I understand. What about the other changes? There are development dependencies missing?

**Comment by ianpartridge** [comment]
Those are fine, thanks.

**Comment by tiagomartinho** [comment]
@ianpartridge I just left the missing dependencies and README changes. It's that ok?

**Pull request merged**
